language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Wand/Firmware/Accelerometer_Test/Accelerometer_Test.ino PLATFORMIO_CI_EXTRA_ARGS="--board=uno"
    - PLATFORMIO_CI_SRC=Wand/Firmware/RGB_Led_Test/RGB_Led_Test.ino PLATFORMIO_CI_EXTRA_ARGS="--board=uno"
    - PLATFORMIO_CI_SRC=Wand/Firmware/Thermocouple_Test/Thermocouple_Test.ino PLATFORMIO_CI_EXTRA_ARGS="--board=uno"
    - PLATFORMIO_CI_SRC=Wand/Firmware/Thermocouple_MAX6675_Test/Thermocouple_MAX6675_Test.ino PLATFORMIO_CI_EXTRA_ARGS="--board=uno"
    - PLATFORMIO_CI_SRC=Wand/Firmware/Wand_Firmware PLATFORMIO_CI_EXTRA_ARGS="--project-conf=Wand/Firmware/Wand_Firmware/platformio.ini"
    - PLATFORMIO_CI_SRC=Base/Firmware/Base_Firmware PLATFORMIO_CI_EXTRA_ARGS="--project-conf=Base/Firmware/Base_Firmware/platformio.ini"

install:
    - pip install -U platformio

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/11/I2Cdevlib-Core
    - platformio lib install 11
    # http://platformio.org/lib/show/107/I2Cdevlib-MPU6050
    - platformio lib install 107
    # http://platformio.org/lib/show/84/Adafruit-MAX31885
    - platformio lib install 84
    # http://platformio.org/lib/show/558/Adafruit-MAX6675
    - platformio lib install 558

script:
    - platformio ci $PLATFORMIO_CI_EXTRA_ARGS

