language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Wand/Firmware/Accelerometer_Test/Accelerometer_Test.ino

install:
    - pip install -U platformio

script:
    - platformio ci --board=TYPE_1 --board=TYPE_2 --board=TYPE_N
